# Generated by Django 6.0 on 2025-12-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrusadeFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Flyer title (e.g., Nigeria Crusade 2025)', max_length=200)),
                ('image', models.ImageField(help_text='Upload crusade flyer image', upload_to='crusade_flyers/')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on donation page')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crusade Flyer',
                'verbose_name_plural': 'Crusade Flyers',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrusadeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_donors', models.IntegerField(default=0)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('crusades_planned', models.IntegerField(default=12)),
                ('countries_list', models.TextField(blank=True, help_text='Comma-separated list of countries (e.g., Nigeria, Ghana, Kenya)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crusade Statistics',
                'verbose_name_plural': 'Crusade Statistics',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('one-time', 'One-Time'), ('monthly', 'Monthly')], default='one-time', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], default='card', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Prayer request or message', null=True)),
                ('payment_gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], default='paystack', help_text='Payment gateway used for this donation', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Unique payment reference from gateway', max_length=200, null=True)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe payment intent ID (legacy)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='donations.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='donations.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
