# Generated by Django 6.0 on 2026-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='USD', help_text='Currency for this donation', max_length=3),
        ),
    ]
