# Generated by Django 4.2.7 on 2026-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_ministryimage_alter_crusadeflyer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person's name (e.g., Mary Johnson)", max_length=200)),
                ('location', models.CharField(help_text='City, Country (e.g., Lagos, Nigeria)', max_length=200)),
                ('testimony_text', models.TextField(help_text='The full testimony content')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website?')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
