# Generated by Django 4.2.7 on 2026-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_crusadeflyer_id_alter_crusadestats_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('home_church', models.CharField(blank=True, max_length=200)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('session_preference', models.CharField(blank=True, choices=[('morning', 'Morning Sessions'), ('evening', 'Evening Sessions'), ('all', 'All Sessions'), ('weekends', 'Weekends Only')], max_length=20)),
                ('departments', models.CharField(blank=True, help_text='Comma-separated department keys', max_length=200)),
                ('experience', models.CharField(blank=True, choices=[('first', 'First-time volunteer'), ('1-2', '1–2 crusades'), ('3-5', '3–5 crusades'), ('6+', '6+ crusades')], max_length=10)),
                ('special_skills', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
