# Generated by Django 4.2.7 on 2026-04-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='needs_transport',
            field=models.BooleanField(default=False),
        ),
    ]
