# Generated by Django 4.2.7 on 2026-04-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_volunteer_needs_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
